; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
	-I src/Task_FreeRTOS/Task-Sensor/Task1_readSensor-TDS
	-I src/Task_FreeRTOS/Task-Sensor/Task2_readSensor-Turbidity
	-I src/Task_FreeRTOS/Task-Sensor/Task3_readSensor-pH
	-I src/Task_FreeRTOS/Task-IoT/Task1_MQTT
	-I src/Task_FreeRTOS/Task-IoT/Task2_WiFi
lib_deps = 
	adafruit/Adafruit ADS1X15@^2.6.2
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.2.2
	lovyan03/LovyanGFX@^1.2.21
	lvgl/lvgl@^9.5.0
lib_ldf_mode = deep+
lib_extra_dirs = 
	lib/IoT_Lib
	lib/Sensor_Lib
	lib/TFT_Disp_Lib